# Generated by Django 4.2.30 on 2026-09-11 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_allow_guest_visits'),
        ('orders', '0004_pedido_payment_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopedido',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productopedido',
            name='nombre_tienda',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productopedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producto'),
        ),
    ]
