# Generated by Django 4.2.30 on 2026-09-25 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_stripe_subscription'),
        ('orders', '0007_order_line_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopedido',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productopedido',
            name='cancelado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Subpedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('preparacion', 'En preparación'), ('listo', 'Listo para recoger'), ('recogido', 'Recogido'), ('cancelado', 'Cancelado')], default='preparacion', max_length=20)),
                ('requiere_reembolso', models.BooleanField(default=False)),
                ('cancelado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpedidos', to='orders.pedido')),
                ('tienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subpedidos', to='stores.tienda')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='productopedido',
            name='subpedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.subpedido'),
        ),
        migrations.AddConstraint(
            model_name='subpedido',
            constraint=models.UniqueConstraint(fields=('pedido', 'tienda'), name='unique_suborder_per_store'),
        ),
    ]
