# Generated by Django 4.2.30 on 2026-05-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('cultura_ocio', 'Cultura y ocio'), ('hogar_bricolaje', 'Hogar y bricolaje'), ('salud_bienestar', 'Salud y bienestar'), ('tecnologia_electronica', 'Tecnología y electrónica'), ('floristeria_jardineria', 'Floristería y jardinería'), ('alimentacion_bebidas', 'Alimentación y bebidas'), ('moda_complementos', 'Moda y complementos'), ('papeleria_oficina', 'Papelería y oficina')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
