# Generated by Django 4.2.30 on 2026-05-12 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('products', '0003_tienda_producto_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='stores.tienda'),
        ),
        migrations.DeleteModel(
            name='Tienda',
        ),
    ]
