# Generated by Django 4.2.30 on 2026-09-11 20:53

from django.db import migrations, models
import django.db.models.deletion


def delete_products_without_store(apps, schema_editor):
    Producto = apps.get_model('products', 'Producto')
    Producto.objects.filter(tienda__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_make_store_creation_date_required'),
        ('products', '0008_allow_guest_visits'),
    ]

    operations = [
        migrations.RunPython(delete_products_without_store, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='stores.tienda'),
        ),
    ]
